<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SUBASH" ignored="0" name="RetryTest" tests="8" failures="2" timestamp="11 Dec 2018 07:19:12 GMT" time="0.316" errors="0">
  <testcase name="test1" time="0.049" classname="com.Mytests.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="com.Mytests.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.Mytests.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.016" classname="com.Mytests.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.Mytests.RetryTest.test1(RetryTest.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.043" classname="com.Mytests.RetryTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.008" classname="com.Mytests.RetryTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="com.Mytests.RetryTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.011" classname="com.Mytests.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.Mytests.RetryTest.test2(RetryTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetryTest -->
